### ISSUE TITLE
Menu bar values not updating when resuming macOS from sleep

### ISSUE THREAD

**Issue by linkineo** [AlexStepanischev/WeatherDock#1]
Thanks for your great app, it's really nice, with a great UI :-)
However, whenever I put my laptop to sleep for a few hours and resume, the weather data shown in the menu bar is not updating. I need to click manually on it so that it updates. Is it possible to catch the event when the system resumes from sleep and update it automatically ?

Tested under macOS 12.2.1

**Comment by AlexStepanischev** [comment]
Thank you for reporting this one, It's known to me, I'll try to figure out how to fix that.

**Comment by AlexStepanischev** [comment]
Fixed in version 2.0
