### ISSUE TITLE
Missing information 

### ISSUE THREAD

**Issue by thoroc** [AlexStepanischev/WeatherDock#3]
Since a picture is worth a 1000 words:

<img width="436" alt="Screenshot 2022-11-24 at 21 31 56" src="https://user-images.githubusercontent.com/2297889/203865640-33b618d1-6339-41d2-8e18-ca7fb7df3f62.png">

As you can see half the information doesn't seems to be displayed. I have allowed the app to use the current location in the mac settings.

MBP 13" 2020, MacOS 12.6.1

**Comment by uhKieran** [comment]
I've had this problem too just to further add receipts to their claims. Started around a week ago for me. I've done the same as the author has, allowing location use, still nothing. It's been really on and off, sometimes it works, sometimes it doesn't.

macOS 12.4.0

**Comment by AlexStepanischev** [comment]
Hi, yes, it happens because OpenWeather API data exceeded free daily limits. I do not want to pay for it, since I'm migrating app to use Apple's WeatherKit which is available only starting from MacOs 13. So, the only workaround is to update to MacOs13 and switch data source in settings to Apple Weather.

**Comment by uhKieran** [comment]
> Hi, yes, it happens because OpenWeather API data exceeded free daily limits. I do not want to pay for it, since I'm migrating app to use Apple's WeatherKit which is available only starting from MacOs 13. So, the only workaround is to update to MacOs13 and switch data source in settings to Apple Weather.

Short of upgrading to macOS 13, would it be a better idea to compile it ourselves and use our own API key? That way the limit won't be exceeded.

**Comment by AlexStepanischev** [comment]
@uhio You could checkout repo, add your API key and run it, no problem there. However, latest release version of app in Mac App Store currently works fine, no issues there.

**Comment by markdrobinson** [comment]
How do you change the data source in settings? I don't see an option for that.

**Comment by AlexStepanischev** [comment]
@markdrobinson In latest app version there is no such option
